<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {

   $services = array(
    array('id' => '1','category_id' => '66','title' => 'Branding & Digital Marketing','slug' => 'get-real-time-visibility-into-every-expense','icon' => '/assets/frontend/images/icon/icon_74.svg','preview' => '/assets/frontend/images/media/img_57.jpg','overview' => 'Risk management and compliance, when approached strategically, have the potential to go beyond mitigating threats and protecting a company’s operations and reputation.','description' => '<h3><strong>Our Strategy</strong></h3><p>Crafting brand identity with logo, website, and social media design to ensure a strong digital presence and brand <a target="_blank" rel="noopener noreferrer nofollow" href="http://recognition.At">recognition.At</a> vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatu deleniti atque corrupti quos dolores et quas molestias excepturi.</p><ul><li><p><strong>Research &amp; Details Planning</strong></p></li><li><p><strong>AI co-pilot ready to start your job based on research</strong></p></li><li><p><strong>Give you option to choose</strong></p></li><li><p><strong>Get your desire search result and ready to use</strong></p></li></ul>','faqs' => '[{"question":"1. Create Account with email","answer":"I iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi design to ensure a strong."},{"question":"2. Setup your Account","answer":"I iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi design to ensure a strong."}]','is_active' => '1','is_featured' => '1','meta' => '{"title":"Branding & Digital Marketing","image":null,"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum","tags":"service,stori,ai"}','created_at' => '2023-11-15 02:57:49','updated_at' => '2025-04-07 04:57:06'),
    array('id' => '2','category_id' => '70','title' => 'Custom AI Model Training','slug' => 'custom-ai-model-training','icon' => '/uploads/25/06/NUv7e1PCq5FSj9Iu7W82.svg','preview' => '/uploads/25/06/Ib9aeKO1rlP0elwtiEx6.jpg','overview' => 'AI custom model training tailors a pre-trained AI to your specific data, improving accuracy and performance for your unique use case.','description' => '<h3><strong>Our Strategy</strong></h3><p>Crafting brand identity with logo, website, and social media design to ensure a strong digital presence and brand <a target="_blank" rel="noopener noreferrer nofollow" href="http://recognition.At">recognition.At</a> vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatu deleniti atque corrupti quos dolores et quas molestias excepturi.</p><ul><li><p><strong>Research &amp; Details Planning</strong></p></li><li><p><strong>AI co-pilot ready to start your job based on research</strong></p></li><li><p><strong>Give you option to choose</strong></p></li><li><p><strong>Get your desire search result and ready to use</strong></p></li></ul>','faqs' => '[{"question":"1. Create Account with email","answer":"I iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi design to ensure a strong."},{"question":"2. Setup your Account","answer":"I iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi design to ensure a strong."}]','is_active' => '1','is_featured' => '0','meta' => '{"title":"Custom AI Model Training","image":null,"description":"AI custom model training tailors a pre-trained AI to your specific data, improving accuracy and performance for your unique use case.","tags":"ai"}','created_at' => '2025-06-23 17:35:10','updated_at' => '2025-06-23 17:35:10'),
    array('id' => '3','category_id' => '72','title' => 'WhatsApp Web API','slug' => 'whatsapp-web-api','icon' => '/uploads/25/06/ebq5jujqBgu0ykfbuuwy.svg','preview' => '/uploads/25/06/odkErL8xc4tcvFAn5tZo.jpg','overview' => 'WhatsApp Web API lets you send, receive, and automate messages through WhatsApp using your application.','description' => '<h3><strong>Our Strategy</strong></h3><p>Crafting brand identity with logo, website, and social media design to ensure a strong digital presence and brand <a target="_blank" rel="noopener noreferrer nofollow" href="http://recognition.At">recognition.At</a> vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatu deleniti atque corrupti quos dolores et quas molestias excepturi.</p><ul><li><p><strong>Research &amp; Details Planning</strong></p></li><li><p><strong>AI co-pilot ready to start your job based on research</strong></p></li><li><p><strong>Give you option to choose</strong></p></li><li><p><strong>Get your desire search result and ready to use</strong></p></li></ul>','faqs' => '[{"question":"1. Create Account with email","answer":"I iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi design to ensure a strong."},{"question":"2. Setup your Account","answer":"I iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi design to ensure a strong."}]','is_active' => '1','is_featured' => '1','meta' => '{"title":"WhatsApp Web API","image":null,"description":"WhatsApp Web API lets you send, receive, and automate messages through WhatsApp using your application.","tags":"whatsapp"}','created_at' => '2025-06-23 17:56:49','updated_at' => '2025-06-23 17:56:49'),
    array('id' => '4','category_id' => '71','title' => 'AI / NLP Chatbot','slug' => 'ai-nlp-chatbot','icon' => '/uploads/25/06/OSmXTNRgNLMNJ9Or4mrk.svg','preview' => '/uploads/25/06/oZFa79NnPt44T2SxMQx5.jpg','overview' => 'A chatbot is an AI-powered tool that simulates human conversation, allowing users to interact through text or voice for support, information, or automation.','description' => '<h3><strong>Our Strategy</strong></h3><p>Crafting brand identity with logo, website, and social media design to ensure a strong digital presence and brand <a target="_blank" rel="noopener noreferrer nofollow" href="http://recognition.At">recognition.At</a> vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatu deleniti atque corrupti quos dolores et quas molestias excepturi.</p><ul><li><p><strong>Research &amp; Details Planning</strong></p></li><li><p><strong>AI co-pilot ready to start your job based on research</strong></p></li><li><p><strong>Give you option to choose</strong></p></li><li><p><strong>Get your desire search result and ready to use</strong></p></li></ul>','faqs' => '[{"question":"1. Create Account with email","answer":"I iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi design to ensure a strong."},{"question":"2. Setup your Account","answer":"I iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi design to ensure a strong."}]','is_active' => '1','is_featured' => '0','meta' => '{"title":"AI \\/ NLP Chatbot","image":null,"description":"A chatbot is an AI-powered tool that simulates human conversation, allowing users to interact through text or voice for support, information, or automation.","tags":"ai chatbot"}','created_at' => '2025-06-23 17:59:01','updated_at' => '2025-06-23 17:59:01'),
    array('id' => '5','category_id' => '66','title' => 'Button or interactive message','slug' => 'button-or-interactive-message','icon' => '/uploads/25/06/uurIynf7gowd1MAIcYjv.svg','preview' => '/uploads/25/06/XkDwzxDtzyXCrVdzmkMc.jpg','overview' => 'WhatsApp Button Message lets you send interactive messages with clickable buttons, making it easy for users to reply or take action quickly.','description' => '<h3><strong>Our Strategy</strong></h3><p>Crafting brand identity with logo, website, and social media design to ensure a strong digital presence and brand <a target="_blank" rel="noopener noreferrer nofollow" href="http://recognition.At">recognition.At</a> vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatu deleniti atque corrupti quos dolores et quas molestias excepturi.</p><ul><li><p><strong>Research &amp; Details Planning</strong></p></li><li><p><strong>AI co-pilot ready to start your job based on research</strong></p></li><li><p><strong>Give you option to choose</strong></p></li><li><p><strong>Get your desire search result and ready to use</strong></p></li></ul>','faqs' => '[{"question":"1. Create Account with email","answer":"I iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi design to ensure a strong."},{"question":"2. Setup your Account","answer":"I iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi design to ensure a strong."}]','is_active' => '1','is_featured' => '0','meta' => '{"title":"Button or interactive message","image":null,"description":"WhatsApp Button Message lets you send interactive messages with clickable buttons, making it easy for users to reply or take action quickly.","tags":"WhatsML"}','created_at' => '2025-06-23 18:01:35','updated_at' => '2025-06-23 18:01:35'),
    array('id' => '6','category_id' => '66','title' => 'Phone Number Scraper','slug' => 'phone-number-scraper','icon' => '/uploads/25/06/OzZgCciyfbaVDFkufqg5.svg','preview' => '/uploads/25/06/Yei7H3Riofy4ZD7N2OLS.jpg','overview' => 'A Phone Number Scraper for Google Maps is a tool that extracts business phone numbers and contact details directly from Google Maps listings. It\'s commonly used for lead generation and local business outreach.','description' => '<h3><strong>Our Strategy</strong></h3><p>Crafting brand identity with logo, website, and social media design to ensure a strong digital presence and brand <a target="_blank" rel="noopener noreferrer nofollow" href="http://recognition.At">recognition.At</a> vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatu deleniti atque corrupti quos dolores et quas molestias excepturi.</p><ul><li><p><strong>Research &amp; Details Planning</strong></p></li><li><p><strong>AI co-pilot ready to start your job based on research</strong></p></li><li><p><strong>Give you option to choose</strong></p></li><li><p><strong>Get your desire search result and ready to use</strong></p></li></ul>','faqs' => '[{"question":"1. Create Account with email","answer":"I iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi design to ensure a strong."},{"question":"2. Setup your Account","answer":"I iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi design to ensure a strong."}]','is_active' => '1','is_featured' => '1','meta' => '{"title":"Phone Number Scraper","description":"A Phone Number Scraper for Google Maps is a tool that extracts business phone numbers and contact details directly from Google Maps listings. It\'s commonly used for lead generation and local business outreach.","tags":"WhatsML"}','created_at' => '2025-06-23 18:09:02','updated_at' => '2025-06-23 18:09:13')
  );


    Service::insert($services);
  }
}
